# Generated by Django 5.2.8 on 2025-11-30 09:56

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('original_date', models.DateField(verbose_name='Дата оригинального документа')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('document_file', models.FileField(upload_to=archive.models.document_upload_path, verbose_name='Файл документа')),
                ('document_type', models.CharField(choices=[('photo', 'Фотография'), ('scan', 'Скан документа'), ('multipage', 'Многостраничный документ')], default='photo', max_length=20, verbose_name='Тип документа')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=archive.models.thumbnail_upload_path, verbose_name='Миниатюра')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова (через запятую)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Поисковый запрос')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата по')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество результатов')),
            ],
            options={
                'verbose_name': 'Лог поиска',
                'verbose_name_plural': 'Логи поиска',
                'ordering': ['-search_date'],
            },
        ),
    ]
